# Generated by Django 5.2.3 on 2025-07-10 18:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VbucksSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SKIN', 'Skin'), ('EMOTE', 'Emote'), ('BUNDLE', 'Bundle'), ('GIFT', 'Gift'), ('BP', 'Battle Pass'), ('OTHER', 'Other')], default='SKIN', max_length=10)),
                ('vbucks_spent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('refunded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vbucks_spendings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'V-Bucks Spending',
                'verbose_name_plural': 'V-Bucks Spendings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vbucks_returned', models.PositiveIntegerField(editable=False, help_text='Automatically set to match original purchase amount', verbose_name='V-Bucks Returned')),
                ('refund_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Refund Date')),
                ('reason', models.CharField(blank=True, choices=[('ACCIDENTAL', 'Accidental Purchase'), ('DISAPPOINTED', 'Item Disappointed Me'), ('OTHER', 'Other')], help_text='Select the reason for this refund', max_length=200, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('original_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='vbucks_tracker.vbucksspending', verbose_name='Original Purchase')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-refund_date'],
            },
        ),
        migrations.CreateModel(
            name='RealMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VB', 'V-Bucks'), ('CREW', 'Fortnite Crew'), ('QUEST', 'Quest Pack'), ('PACK', 'Skin Pack'), ('OTHER', 'Other')], default='VB', max_length=10)),
                ('source_name', models.CharField(help_text="Specify the exact name, e.g. 'Season 7 Battle Pass' or 'Quest Pack 3'", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('vbucks_earned', models.PositiveIntegerField(default=0, help_text='Amount of V-Bucks received from this transaction')),
                ('date', models.DateField()),
                ('currency', models.CharField(choices=[('BGN', 'BGN (Bulgarian Lev)'), ('EUR', 'EUR (Euro)'), ('USD', 'USD (US Dollar)'), ('GBP', 'GBP (British Pound)')], default='BGN', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_money_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Real Money Transaction',
                'verbose_name_plural': 'Real Money Transactions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='vbucks_trac_user_id_0739f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='VbucksEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BP', 'Battle Pass'), ('CREW', 'Fortnite Crew'), ('QUEST', 'Quest Pack')], default='BP', max_length=10)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('earning_name', models.CharField(blank=True, help_text='Optional name for this earning', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vbucks_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'V-Bucks Earning',
                'verbose_name_plural': 'V-Bucks Earnings',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='vbucks_trac_user_id_1dd21e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vbucksspending',
            index=models.Index(fields=['user', 'date'], name='vbucks_trac_user_id_84523b_idx'),
        ),
        migrations.AddIndex(
            model_name='vbucksspending',
            index=models.Index(fields=['refunded'], name='vbucks_trac_refunde_5b7c90_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user', 'refund_date'], name='vbucks_trac_user_id_890c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['original_purchase'], name='vbucks_trac_origina_25235e_idx'),
        ),
    ]
